= Rapport d’avancement du groupe 2.1
PACT groupe 2.1
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]
:doctype: book
:stem: latexmath
:source-highlighter: coderay
:toc-title: Table des matières
:toc: macro
:sectnums:
:imagesdir: images


// Partie non numérotée
:sectnums!:
== « E-Maisel »

=== Membres du groupe

* Berenger Zoé
* Boulanger Paul
* Fang Guyu 
* Hayes Soline
* Laborde Florian
* Lanvin Alexandre

=== Tuteur

* Le Feuvre Jean 

=== Encadrant génie logiciel

* David Aurélien

== Résumé du sujet choisi en français (PAN1)

Notre projet, nommé “e-Maisel”, consiste en la mise en place d’une application
Android permettant de faciliter la vie quotidienne des habitants de la maison
des élèves. Plus précisément, le but est de permettre aux utilisateurs d’accéder
aux machines-à-laver disponibles et, le cas échéant, de pouvoir les réserver.
L’application doit de surcroît afficher le nombre de personnes dans la cuisine
d’un étage défini par l’habitant de la Maisel qui peut aussi, de la même
manière, voir quelles plaques sont occupées. Elle présente des fonctionnalités
supplémentaires suivantes : l’affichage d’une notification dans les cas de
contrôle de ménage ou de loyer à régler, le fait de pouvoir savoir si la
personne a ou non du courrier et l’affichage des statistiques du site Babar.
Ce projet s’inscrit dans le thème Campus du futur : il a en effet été pensé
pour la Maisel, mais pourra aussi être adapté pour les futurs résidences des
étudiants de Télécom.

== English Summary (PAN1)

Our project called « E-Maisel », is based on the elaboration of an Android 
application that can make the everyday life of the students in the “Maison des
élèves” easier. More precisely, the aim of it is to enable users to access the
list of the available washing machines from their phone and when some are, to
even give them the possibility to book one. Moreover, it displays how many
people are in a given kitchen and the student can also see how many hotplates
are being used. It also has other functionalities such as the submission of a
notification for a cleaning check or for when the rent is due, mailbox-checking
and the printing of the bar website’s statistics. This project is part of the
theme Campus of the future : he was indeed designed for the Maisel, but could
also be adapted to the futur housings of the students of Télécom.

////
*Notes concenant le rapport*

Les différentes pages du document sont rédigées en utilisant le langage
AsciiDoc. Le squelette de rapport contient des exemples avec entre autre:

* des images,
* des liens,
* des équations.

La structure du rapport (parties, sections et la relation avec les
differents fichiers) se trouve dans le fichier courant.
////

// en PDF on ne peut pas controler la position de la toc
// Macros non supportées
ifndef::backend-pdf[]
== Table des matières
:toc-title:
toc::[]
endif::[]

// On numérote le reste des sections
:sectnums:

== Étude d’antériorité et justification de la proposition (PAN1)

include::proposition/proposition.adoc[Description de la proposition]

include::proposition/etat-de-l-art.adoc[Description de l’état de l’art]

== Scénarios d’usage (PAN1)

include::scenario/scenario.adoc[Scénarios d’usage]

== Architecture du projet (PAN1)

include::architecture/schema.adoc[Schéma d’architecture]

include::architecture/interfaces.adoc[Description des interfaces]

include::architecture/sequence.adoc[Diagramme de séquence]

include::architecture/ihm.adoc[Interface utilisateur graphique]

//include::architecture/taches.adoc[Tableau détaillé des tâches]

== Organisation du projet (PAN1)

include::organisation/plannification.adoc[Diagramme de planification temporel des tâches]

include::organisation/repartition.adoc[Répartition des élèves par module]

include::organisation/plan-tests.adoc[Plans de test (PAN2+)]

include::organisation/avancement.adoc[Diagramme d’avancement des tâches (PAN2+)]

'''''

[bibliography]
== Bibliographie (PAN1+)

include::References.adoc[Bibliographie]

'''''

== Annexes

include::annexes/identite.adoc[Fiche d’identité du groupe (PAN1)]

include::annexes/modifications.adoc[Modifications (PAN2+)]

include::annexes/reunions.adoc[Comptes Rendus de réunions]

include::annexes/avancement.adoc[Avancement des modules]

include::annexes/moduleHardware.adoc[Avancement module Hardware]

include::annexes/moduleAndroid.adoc[Avancement module Android]

include::annexes/moduleBaseDeDonnées.adoc[Avancement module Database]

include::annexes/moduleCommunication.adoc[Avancement module Communication]
