=== Description de l’état de l’art
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]

La diffusion des nouvelles technologies permettent maintenant de connecter des objets, des voitures… et même des logements. Dans ce domaine, après la domotique, l’idée innovante est la centralisation de services et de fonctionnalités sur une application mobile <<rapport/References.adoc#a1,[1]>> : chauffage, serrure, contrôle des appareils électriques, boîte aux lettres, etc. Ce concept est également adaptable à des résidences étudiantes, qui accueillent de surcroît des personnes nées avec la technologie numérique : une résidence connectée de ce type verra le jour en 2018 <<rapport/References.adoc#a2,[2]>>. Ainsi, notre projet s’inscrit dans une démarche d’innovation très actuelle.

Tout d’abord, les cuisines connectées apparaissent de plus en plus sur les marchés. Entre réfrigérateurs intelligents, fours connectés ou théière et cafetière connectées <<rapport/References.adoc#a3,[3]>>, tous les ustensiles de la maison sont maintenant liés aux nouvelles technologies et peuvent être contrôlés à distance pour un plus grand confort. Notre projet propose aussi de connecter les cuisines d’étage de la Maison des élèves (Maisel), seulement cette connexion ne concerne pas les ustensiles mais a pour but d’analyser et de visualiser les flux d’affluence vers les cuisines. Des capteurs détectant la mise en marche des plaques de cuisson et deux capteurs de présence à la porte permettront aux étudiants de savoir quelle cuisine est libre directement depuis leur chambre à l’aide de notre application.

Il existe également des réseaux de machines à laver connectées. Par exemple, Lavomatique propose une centrale de laverie automatisée dont toutes les fonctions sont centralisées sur une application pour le gérant <<rapport/References.adoc#a4,[4]>>. La gestion à distance d’une laverie est ainsi grandement facilitée. Mais de notre côté, nous nous placerons du point de vue des usagers : il s’agira de savoir à distance si des machines à laver sont disponibles, et le cas échéant d’en réserver. L’étudiant n’a donc plus besoin de descendre jusqu’au premier étage de la Maisel avec son linge dans l’espoir de trouver de la place dans les laveries. L’application pourrait également nous permettre de récolter des données statistiques sur l’utilisation des machines, comme dans l’exemple de la Lavobox.

Enfin, les nouvelles technologies touchent aussi les boîtes aux lettres. En effet, de plus en plus de logements adoptent des détecteurs de courrier, ce qui permet de savoir si l’on a reçu du courrier sans qu’il y ait besoin d’aller voir sur place. Ce détecteur fonctionne avec un détecteur de présence qui détecte donc une ouverture de porte ou l’arrivée d’une lettre <<rapport/References.adoc#a5,[5]>>. Pour notre projet à la Maisel, les boîtes aux lettres étant ouvertes nous préférons utiliser des bouttons permettant d'annoncer l’arrivée d’une lettre. Ainsi, l’étudiant peut savoir depuis sa chambre s’il a du courrier au lieu de descendre jusqu’au rez de chaussée. 

En conclusion, notre projet est cohérent avec le mouvement général vers le “tout connecté”. Il n’est pas le premier à proposer ce genre de services centralisés sur une application mobile, mais il est parfaitement adapté à l’utilisation voulue pour la Maisel.
